FROM openjdk:11-jre-slim
WORKDIR usr/src
ADD ./target/SpringCloudGateway-0.0.1-SNAPSHOT.jar /usr/src/SpringCloudGateway-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","SpringCloudGateway-0.0.1-SNAPSHOT.jar"]
